# vim: sw=2 et

version: '2.4'

services:
  nginx:
    build:
      context: .
      args:
        BUILD_THROTTLE: $BUILD_THROTTLE
        HEADERS_MORE_VERSION: $HEADERS_MORE_VERSION
        NGINX_COMMIT: $NGINX_COMMIT
        NGINX_VERSION: $NGINX_VERSION
        NGX_BROTLI_COMMIT: $NGX_BROTLI_COMMIT
        NJS_COMMIT: $NJS_COMMIT
        NJS_VERSION: $NJS_VERSION
        OPENSSL_CFLAGS: $OPENSSL_CFLAGS
        OPENSSL_VERSION: $OPENSSL_VERSION
    image: ${IMAGE_NAME}:${NGINX_VERSION}
    # command: ["/usr/bin/nginx", "-t"]
    environment:
      # NGINX_HOST_CERT_PATH: "/etc/nginx/ssl"
      # NGINX_HOST: "localhost"
      # NGINX_HTTP_REDIRECT_LOCATION: "https://localhost:42662$$request_uri"
      DNS_RESOLVER: ${DNS_RESOLVER:-1.1.1.1}
      GROUP_ID: ${GROUP_ID:-1001}
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ${NGINX_ENVSUBST_TEMPLATE_SUFFIX:-.conf}
      NGINX_LOG_FORMAT_NAME: ${NGINX_LOG_FORMAT_NAME:-main}
      NGINX_SERVER_HEADER: ${NGINX_SERVER_HEADER:-}
      NGINX_WORKER_PROCESSES: ${NGINX_WORKER_PROCESSES:-2}
      TZ: ${TZ:-UTC}
      USER_ID: ${USER_ID:-1001}
    # volumes:
      # - "./webroot:/var/www/html:ro,z"
      # - "./njs/njs.conf:/config/njs.conf:ro,z"
      # - "./njs/http.js:/config/njs/http.js:ro,z"
      # - "./njs/localhost.conf:/config/sites/localhost.conf:ro,z"
      # - "./src/etc/nginx/nginx.conf:/config/nginx.conf:ro,z"
    ports:
      - "0.0.0.0:42661:80"
      - "127.0.0.1:42662:81" # stub_status
      - "0.0.0.0:42663:443"

