# vim: sw=2 et

version: '2.4'

services:
  nginx:
    build:
      context: .
      args:
        ALPINE_VERSION: $ALPINE_VERSION
        BUSYBOX_VERSION: $BUSYBOX_VERSION
        CFLAGS_ADD: $CFLAGS_ADD
        HEADERS_MORE_VERSION: $HEADERS_MORE_VERSION
        NGINX_COMMIT: $NGINX_COMMIT
        NGINX_VERSION: $NGINX_VERSION
        NGX_BROTLI_COMMIT: $NGX_BROTLI_COMMIT
        NJS_COMMIT: $NJS_COMMIT
        OPENSSL_VERSION: $OPENSSL_VERSION
        PCRE_VERSION: $PCRE_VERSION
        ZLIB_VERSION: $ZLIB_VERSION
    image: compilenix/nginx:${NGINX_VERSION}
    container_name: nginx
    environment:
      DNS_RESOLVER: $DNS_RESOLVER
      NGINX_LOG_FORMAT_NAME: ${NGINX_LOG_FORMAT_NAME:-main}
      NGINX_WORKER_PROCESSES: ${NGINX_WORKER_PROCESSES:-2}
      TZ: ${TZ:-UTC}
    volumes:
      - "./webroot:/var/www/html:ro,z"
    ports:
      - "0.0.0.0:42661:2080"
      - "0.0.0.0:42662:2443"

