GET https://127.0.0.1:{{HTTPS_PORT}}/autoindex/
HTTP/2 200
Content-Type: text/html
```
<html>
<head><title>Index of /autoindex/</title>
<meta name="color-scheme" content="light dark">
</head>
<body>
<h1>Index of /autoindex/</h1><hr><pre><a href="../">../</a>
<a href="test_1.txt">test_1.txt</a>                                         31-Mar-2025 00:07                   7
<a href="test_2.txt">test_2.txt</a>                                         31-Mar-2025 00:08                1650
</pre><hr></body>
</html>
```
